name: CI

on:
  pull_request:
  push:

env:
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COVERAGE: '0'

jobs:
  psalm:
    name: "Psalm - Static Analysis"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        php:
          - '7.4'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, bcmath, curl, openssl, mbstring, mongodb
          ini-values: memory_limit=-1
          tools: pecl, composer, psalm
          coverage: none
      - name: Install dependencies
        run: composer install --dev
      - name: Run psalm
        run: ./vendor/bin/psalm --output-format=github

  # phpstan
  phpstan:
    name: "PHPStan"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        php:
          - '7.4'
      fail-fast: false
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpstan

      - name: Run PHPStan
        run: phpstan analyse src